spring:
  application:
    name: payment-service

grpc:
  server:
    port: 9090
    health-service-enabled: true
    reflection-service-enabled: true

logging:
  level:
    com.example.paymentservice: INFO
    net.devh.boot.grpc: INFO
