spring:
  application:
    name: payment-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8081/realms/spring-grpc}
  grpc:
    server:
      port: 9090
      health:
        enabled: true
      reflection:
        enabled: true

logging:
  level:
    com.example.paymentservice: INFO
    org.springframework.grpc: INFO
