server:
  port: 8080

spring:
  application:
    name: order-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8081/realms/spring-grpc}

grpc:
  client:
    payment-service:
      address: static://localhost:9090
      negotiation-type: plaintext
      enable-keep-alive: true
      keep-alive-time: 30s

logging:
  level:
    com.example.orderservice: INFO
    net.devh.boot.grpc: INFO
